// empty-arrays-example v1.0.0 75ca3ce4ef386d2ecd1a8a1001c47885974a3cb7
// --
// Code generated by webrpc-gen@v0.42.0 with ../../../gen-golang generator. DO NOT EDIT.
//
// webrpc-gen -schema=empty_arrays.ridl -target=../../../gen-golang -pkg=main -server -client -fixEmptyArrays=true -out=./empty_arrays.gen.go
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/url"
	"slices"
	"strings"
)

// WebRPC description and code-gen version
func WebRPCVersion() string {
	return "v1"
}

// Schema version of your RIDL schema
func WebRPCSchemaVersion() string {
	return "v1.0.0"
}

// Schema hash generated from your RIDL schema
func WebRPCSchemaHash() string {
	return "75ca3ce4ef386d2ecd1a8a1001c47885974a3cb7"
}

//
// Client interface
//

type EmptyArraysClient interface {
	// Succinct: served by the generic succinctHandler.
	GetReport(ctx context.Context, getReportRequest GetReportRequest) (*GetReportResponse, error)
	// Multiple return values: served by a per-method handler that builds an
	// anonymous response struct, with a list returned at the top level.
	ListReports(ctx context.Context) ([]*Report, uint32, error)
}

//
// Server interface
//

type EmptyArraysServer interface {
	// Succinct: served by the generic succinctHandler.
	GetReport(ctx context.Context, getReportRequest GetReportRequest) (*GetReportResponse, error)
	// Multiple return values: served by a per-method handler that builds an
	// anonymous response struct, with a list returned at the top level.
	ListReports(ctx context.Context) ([]*Report, uint32, error)
}

//
// Schema types
//

type Item struct {
	Tags []string `json:"tags"`
}

func (x *Item) initNilSlices() {
	if x == nil {
		return
	}
	if x.Tags == nil {
		x.Tags = []string{}
	}
}

type Report struct {
	// Required list: always an array on the wire, never null.
	Required []string `json:"required"`
	// Optional list: absent when unset, [] when explicitly empty.
	Optional []string `json:"optional,omitzero"`
	// Required list of structs: the elements get the same treatment.
	Items []*Item `json:"items"`
	// Nested lists are walked all the way down.
	Matrix [][]string `json:"matrix"`
	// Required maps get the same treatment as required lists.
	Counts map[string]uint32 `json:"counts"`
	// Map values are walked too, both the lists and the structs.
	Buckets   map[string][]string `json:"buckets"`
	ByName    map[string]*Item    `json:"byName"`
	OptCounts map[string]uint32   `json:"optCounts,omitzero"`
	// The schema pins its own Go type, so the generator leaves it alone.
	// An empty json.RawMessage is not valid JSON and would fail to marshal.
	Raw   json.RawMessage `json:"raw"`
	Label *string         `json:"label,omitzero"`
	Count uint32          `json:"count"`
}

func (x *Report) initNilSlices() {
	if x == nil {
		return
	}
	if x.Required == nil {
		x.Required = []string{}
	}
	if x.Items == nil {
		x.Items = []*Item{}
	}
	for i0 := range x.Items {
		x.Items[i0].initNilSlices()
	}
	if x.Matrix == nil {
		x.Matrix = [][]string{}
	}
	for i0 := range x.Matrix {
		if x.Matrix[i0] == nil {
			x.Matrix[i0] = []string{}
		}
	}
	if x.Counts == nil {
		x.Counts = map[string]uint32{}
	}
	if x.Buckets == nil {
		x.Buckets = map[string][]string{}
	}
	for k0 := range x.Buckets {
		if x.Buckets[k0] == nil {
			x.Buckets[k0] = []string{}
		}
	}
	if x.ByName == nil {
		x.ByName = map[string]*Item{}
	}
	for k0 := range x.ByName {
		x.ByName[k0].initNilSlices()
	}
}

type GetReportRequest struct {
	Id string `json:"id"`
}

func (x *GetReportRequest) initNilSlices() {
	if x == nil {
		return
	}
}

type GetReportResponse struct {
	Report *Report `json:"report"`
}

func (x *GetReportResponse) initNilSlices() {
	if x == nil {
		return
	}
	x.Report.initNilSlices()
}

//
// Client
//

const EmptyArraysPathPrefix = "/rpc/EmptyArrays/"

type emptyArraysClient struct {
	client HTTPClient
	urls   [2]string
}

func NewEmptyArraysClient(addr string, client HTTPClient) EmptyArraysClient {
	prefix := serviceURL(addr, EmptyArraysPathPrefix)
	urls := [2]string{
		prefix + "GetReport",
		prefix + "ListReports",
	}
	return &emptyArraysClient{
		client: client,
		urls:   urls,
	}
}

func (c *emptyArraysClient) GetReport(ctx context.Context, getReportRequest GetReportRequest) (*GetReportResponse, error) {
	var out *GetReportResponse
	err := doHTTPRequest(ctx, c.client, c.urls[0], getReportRequest, &out)
	return out, err
}

func (c *emptyArraysClient) ListReports(ctx context.Context) ([]*Report, uint32, error) {
	out := struct {
		Ret0 []*Report `json:"reports"`
		Ret1 uint32    `json:"total"`
	}{}

	err := doHTTPRequest(ctx, c.client, c.urls[1], nil, &out)

	return out.Ret0, out.Ret1, err
}

//
// Server
//

type WebRPCServer interface {
	http.Handler
}

type Options struct {
	OnError   func(r *http.Request, rpcErr *WebRPCError)
	OnRequest func(w http.ResponseWriter, r *http.Request) error
}

type emptyArraysService struct {
	EmptyArraysServer
	OnError   func(r *http.Request, rpcErr *WebRPCError)
	OnRequest func(w http.ResponseWriter, r *http.Request) error
}

func NewEmptyArraysServer(svc EmptyArraysServer, options ...*Options) *emptyArraysService {
	server := &emptyArraysService{
		EmptyArraysServer: svc,
	}
	if len(options) > 0 && options[0] != nil {
		server.OnError = options[0].OnError
		server.OnRequest = options[0].OnRequest
	}
	return server
}

func (s *emptyArraysService) Methods() []Method { return methodsFor(ServiceEmptyArrays, s) }

func (s *emptyArraysService) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer func() {
		// In case of a panic, serve a HTTP 500 error and then panic.
		if rr := recover(); rr != nil {
			s.sendErrorJSON(w, r, ErrWebrpcServerPanic.WithCausef("%v", rr))
			panic(rr)
		}
	}()

	w.Header().Set(WebrpcHeader, WebrpcHeaderValue)

	ctx := r.Context()
	ctx = context.WithValue(ctx, HTTPResponseWriterCtxKey, w)
	ctx = context.WithValue(ctx, HTTPRequestCtxKey, r)
	ctx = context.WithValue(ctx, ServiceNameCtxKey, "EmptyArrays")

	r = r.WithContext(ctx)

	var handler func(ctx context.Context, w http.ResponseWriter, r *http.Request)
	switch r.URL.Path {
	case "/rpc/EmptyArrays/GetReport":
		handler = succinctHandler("GetReport", s.EmptyArraysServer.GetReport, s.sendErrorJSON)
	case "/rpc/EmptyArrays/ListReports":
		handler = s.serveListReportsJSON
	default:
		err := ErrWebrpcBadRoute.WithCausef("no webrpc method defined for path %v", r.URL.Path)
		s.sendErrorJSON(w, r, err)
		return
	}

	if r.Method != "POST" {
		w.Header().Add("Allow", "POST") // RFC 9110.
		err := ErrWebrpcBadMethod.WithCausef("unsupported HTTP method %v (only POST is allowed)", r.Method)
		s.sendErrorJSON(w, r, err)
		return
	}

	contentType := r.Header.Get("Content-Type")
	if i := strings.Index(contentType, ";"); i >= 0 {
		contentType = contentType[:i]
	}
	contentType = strings.TrimSpace(strings.ToLower(contentType))

	switch contentType {
	case "application/json":
		if s.OnRequest != nil {
			if err := s.OnRequest(w, r); err != nil {
				rpcErr, ok := err.(WebRPCError)
				if !ok {
					rpcErr = ErrWebrpcEndpoint.WithCause(err)
				}
				s.sendErrorJSON(w, r, rpcErr)
				return
			}
		}

		handler(ctx, w, r)
	default:
		err := ErrWebrpcBadRequest.WithCausef("unsupported Content-Type %q (only application/json is allowed)", r.Header.Get("Content-Type"))
		s.sendErrorJSON(w, r, err)
	}
}

func (s *emptyArraysService) serveListReportsJSON(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	ctx = context.WithValue(ctx, MethodNameCtxKey, "ListReports")

	// Call service method implementation.
	ret0, ret1, err := s.EmptyArraysServer.ListReports(ctx)
	if err != nil {
		rpcErr, ok := err.(WebRPCError)
		if !ok {
			rpcErr = ErrWebrpcEndpoint.WithCause(err)
		}
		s.sendErrorJSON(w, r, rpcErr)
		return
	}

	if ret0 == nil {
		ret0 = []*Report{}
	}
	for i0 := range ret0 {
		ret0[i0].initNilSlices()
	}
	respPayload := struct {
		Ret0 []*Report `json:"reports"`
		Ret1 uint32    `json:"total"`
	}{ret0, ret1}
	respBody, err := json.Marshal(respPayload)
	if err != nil {
		s.sendErrorJSON(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
}

func (s *emptyArraysService) sendErrorJSON(w http.ResponseWriter, r *http.Request, rpcErr WebRPCError) {
	if s.OnError != nil {
		s.OnError(r, &rpcErr)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

func RespondWithError(w http.ResponseWriter, err error) {
	rpcErr, ok := err.(WebRPCError)
	if !ok {
		rpcErr = ErrWebrpcEndpoint.WithCause(err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(rpcErr.HTTPStatus)

	respBody, _ := json.Marshal(rpcErr)
	w.Write(respBody)
}

type sendErrorFunc func(w http.ResponseWriter, r *http.Request, rpcErr WebRPCError)

func succinctHandler[I any, O any](method string, fn func(context.Context, I) (O, error), sendError sendErrorFunc) func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	return func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		ctx = context.WithValue(ctx, MethodNameCtxKey, method)

		reqBody, err := io.ReadAll(r.Body)
		if err != nil {
			sendError(w, r, ErrWebrpcBadRequest.WithCausef("failed to read request data: %w", err))
			return
		}
		defer r.Body.Close()

		var reqPayload I
		if err := json.Unmarshal(reqBody, &reqPayload); err != nil {
			sendError(w, r, ErrWebrpcBadRequest.WithCausef("failed to unmarshal request data: %w", err))
			return
		}

		respPayload, err := fn(ctx, reqPayload)
		if err != nil {
			rpcErr, ok := err.(WebRPCError)
			if !ok {
				rpcErr = ErrWebrpcEndpoint.WithCause(err)
			}
			sendError(w, r, rpcErr)
			return
		}

		if v, ok := any(respPayload).(nilSliceInitializer); ok {
			v.initNilSlices()
		}
		respBody, err := json.Marshal(respPayload)
		if err != nil {
			sendError(w, r, ErrWebrpcBadResponse.WithCausef("failed to marshal json response: %w", err))
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		w.Write(respBody)
	}
}

type method struct {
	name        string
	service     string
	annotations map[string]string
}

func (m *method) Name() string                   { return m.name }
func (m *method) Service() string                { return m.service }
func (m *method) Annotations() map[string]string { return m.annotations }
func (m *method) Annotation(key string) string   { return m.annotations[key] }
func (m *method) HasAnnotation(key string) bool  { _, ok := m.annotations[key]; return ok }

var methods = map[string]*method{
	"/rpc/EmptyArrays/GetReport": {
		name:        "GetReport",
		service:     "EmptyArrays",
		annotations: map[string]string{},
	},
	"/rpc/EmptyArrays/ListReports": {
		name:        "ListReports",
		service:     "EmptyArrays",
		annotations: map[string]string{},
	},
}

func MethodCtx(ctx context.Context) (*method, bool) {
	req := RequestFromContext(ctx)
	if req == nil {
		return nil, false
	}

	m, ok := methods[req.URL.Path]
	return m, ok
}

type Service string

const (
	ServiceEmptyArrays Service = "EmptyArrays"
)

// WebrpcMethods returns a copy of all methods, or only those for the given services.
// For further filtering (e.g. by annotation), use maps.DeleteFunc on the result.
func WebrpcMethods(services ...Service) map[string]*method {
	if len(services) == 0 {
		return maps.Clone(methods)
	}
	out := make(map[string]*method)
	for path, m := range methods {
		if slices.Contains(services, Service(m.service)) {
			out[path] = m
		}
	}
	return out
}

var WebRPCServices = map[string][]string{
	"EmptyArrays": {
		"GetReport",
		"ListReports",
	},
}

// Method pairs an RPC method's metadata with the server that handles it.
// Handler is the server itself, which dispatches by request path.
type Method struct {
	*method
	Path    string
	Handler http.Handler
}

// methodsFor binds every method of service to the handler that serves it.
func methodsFor(service Service, handler http.Handler) []Method {
	var out []Method
	for path, m := range WebrpcMethods(service) {
		out = append(out, Method{method: m, Path: path, Handler: handler})
	}
	return out
}

//
// Client helpers
//

// HTTPClient is the interface used to send HTTP requests. It is fulfilled by *http.Client.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// serviceURL joins addr (a full URL, e.g. "http://localhost:8080") with the
// service path prefix. Malformed addrs fail on the first request.
func serviceURL(addr, prefix string) string {
	u, err := url.Parse(addr)
	if err != nil || u.Host == "" {
		return addr + prefix
	}
	u.RawQuery, u.Fragment = "", ""
	return u.JoinPath(prefix).String()
}

// newRequest makes an http.Request with common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set(WebrpcHeader, WebrpcHeaderValue)
	if headers, ok := HTTPRequestHeaders(ctx); ok {
		for k := range headers {
			for _, v := range headers[k] {
				req.Header.Add(k, v)
			}
		}
	}
	return req, nil
}

// doHTTPRequestRaw makes a request and returns the open *http.Response; the caller must close its body.
func doHTTPRequestRaw(ctx context.Context, client HTTPClient, url string, in, out interface{}) (*http.Response, error) {
	reqBody, err := json.Marshal(in)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("failed to marshal JSON body: %w", err)
	}
	if err = ctx.Err(); err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("aborted because context was done: %w", err)
	}

	req, err := newRequest(ctx, url, bytes.NewBuffer(reqBody), "application/json")
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCausef("could not build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, ErrWebrpcRequestFailed.WithCause(err)
	}

	if resp.StatusCode != 200 {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read server error response body: %w", err)
		}

		var rpcErr WebRPCError
		if err := json.Unmarshal(respBody, &rpcErr); err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal server error: %w", err)
		}
		if rpcErr.Cause != "" {
			rpcErr.cause = errors.New(rpcErr.Cause)
		}
		return nil, rpcErr
	}

	if out != nil {
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to read response body: %w", err)
		}

		err = json.Unmarshal(respBody, &out)
		if err != nil {
			return nil, ErrWebrpcBadResponse.WithCausef("failed to unmarshal JSON response body: %w", err)
		}
	}

	return resp, nil
}

func WithHTTPRequestHeaders(ctx context.Context, h http.Header) (context.Context, error) {
	if _, ok := h["Accept"]; ok {
		return nil, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return nil, errors.New("provided header cannot set Content-Type")
	}

	copied := make(http.Header, len(h))
	for k, vv := range h {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}

	return context.WithValue(ctx, HTTPClientRequestHeadersCtxKey, copied), nil
}

func HTTPRequestHeaders(ctx context.Context) (http.Header, bool) {
	h, ok := ctx.Value(HTTPClientRequestHeadersCtxKey).(http.Header)
	return h, ok
}

// doHTTPRequest makes a request and closes the response body.
func doHTTPRequest(ctx context.Context, client HTTPClient, url string, in, out interface{}) error {
	resp, err := doHTTPRequestRaw(ctx, client, url, in, out)
	if resp != nil {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = ErrWebrpcRequestFailed.WithCausef("failed to close response body: %w", cerr)
		}
	}
	return err
}

//
// Webrpc helpers
//

type contextKey struct {
	name string
}

func (k *contextKey) String() string {
	return "webrpc context value " + k.name
}

var (
	HTTPClientRequestHeadersCtxKey = &contextKey{"HTTPClientRequestHeaders"}
)

var (
	HTTPResponseWriterCtxKey = &contextKey{"HTTPResponseWriter"}
	MethodNameCtxKey         = &contextKey{"MethodName"}
	HTTPRequestCtxKey        = &contextKey{"HTTPRequest"}
	ServiceNameCtxKey        = &contextKey{"ServiceName"}
)

func ServiceNameFromContext(ctx context.Context) string {
	service, _ := ctx.Value(ServiceNameCtxKey).(string)
	return service
}

func MethodNameFromContext(ctx context.Context) string {
	method, _ := ctx.Value(MethodNameCtxKey).(string)
	return method
}

func RequestFromContext(ctx context.Context) *http.Request {
	r, _ := ctx.Value(HTTPRequestCtxKey).(*http.Request)
	return r
}

// Deprecated: Use Go 1.26's new(expr). Migrate automatically with: go fix ./...
func PtrTo[T any](v T) *T { return &v }

func ResponseWriterFromContext(ctx context.Context) http.ResponseWriter {
	w, _ := ctx.Value(HTTPResponseWriterCtxKey).(http.ResponseWriter)
	return w
}

// Implemented by every generated schema struct, so that a generic handler can
// give a response its empty-array treatment without knowing its concrete type.
type nilSliceInitializer interface {
	initNilSlices()
}

//
// Errors
//

type WebRPCError struct {
	Name       string `json:"error"`
	Code       int    `json:"code"`
	Message    string `json:"msg"`
	Cause      string `json:"cause,omitempty"`
	HTTPStatus int    `json:"status"`
	cause      error
}

var _ error = WebRPCError{}

func (e WebRPCError) Error() string {
	if e.cause != nil {
		return fmt.Sprintf("%s %d: %s: %v", e.Name, e.Code, e.Message, e.cause)
	}
	return fmt.Sprintf("%s %d: %s", e.Name, e.Code, e.Message)
}

func (e WebRPCError) Is(target error) bool {
	if target == nil {
		return false
	}
	if rpcErr, ok := target.(WebRPCError); ok {
		return rpcErr.Code == e.Code
	}
	return errors.Is(e.cause, target)
}

func (e WebRPCError) Unwrap() error {
	return e.cause
}

func (e WebRPCError) WithCause(cause error) WebRPCError {
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

func (e WebRPCError) WithCausef(format string, args ...interface{}) WebRPCError {
	cause := fmt.Errorf(format, args...)
	err := e
	err.cause = cause
	err.Cause = cause.Error()
	return err
}

// Webrpc errors
var (
	ErrWebrpcEndpoint       = WebRPCError{Code: 0, Name: "WebrpcEndpoint", Message: "endpoint error", HTTPStatus: 400}
	ErrWebrpcRequestFailed  = WebRPCError{Code: -1, Name: "WebrpcRequestFailed", Message: "request failed", HTTPStatus: 400}
	ErrWebrpcBadRoute       = WebRPCError{Code: -2, Name: "WebrpcBadRoute", Message: "bad route", HTTPStatus: 404}
	ErrWebrpcBadMethod      = WebRPCError{Code: -3, Name: "WebrpcBadMethod", Message: "bad method", HTTPStatus: 405}
	ErrWebrpcBadRequest     = WebRPCError{Code: -4, Name: "WebrpcBadRequest", Message: "bad request", HTTPStatus: 400}
	ErrWebrpcBadResponse    = WebRPCError{Code: -5, Name: "WebrpcBadResponse", Message: "bad response", HTTPStatus: 500}
	ErrWebrpcServerPanic    = WebRPCError{Code: -6, Name: "WebrpcServerPanic", Message: "server panic", HTTPStatus: 500}
	ErrWebrpcInternalError  = WebRPCError{Code: -7, Name: "WebrpcInternalError", Message: "internal error", HTTPStatus: 500}
	ErrWebrpcClientAborted  = WebRPCError{Code: -8, Name: "WebrpcClientAborted", Message: "request aborted by client", HTTPStatus: 400}
	ErrWebrpcStreamLost     = WebRPCError{Code: -9, Name: "WebrpcStreamLost", Message: "stream lost", HTTPStatus: 400}
	ErrWebrpcStreamFinished = WebRPCError{Code: -10, Name: "WebrpcStreamFinished", Message: "stream finished", HTTPStatus: 200}
)

const WebrpcHeader = "Webrpc"

const WebrpcHeaderValue = "webrpc@v0.42.0;gen-golang@unknown;empty-arrays-example@v1.0.0"

type WebrpcGenVersions struct {
	WebrpcGenVersion string
	CodeGenName      string
	CodeGenVersion   string
	SchemaName       string
	SchemaVersion    string
}

func VersionFromHeader(h http.Header) (*WebrpcGenVersions, error) {
	if h.Get(WebrpcHeader) == "" {
		return nil, fmt.Errorf("header is empty or missing")
	}

	versions, err := parseWebrpcGenVersions(h.Get(WebrpcHeader))
	if err != nil {
		return nil, fmt.Errorf("webrpc header is invalid: %w", err)
	}

	return versions, nil
}

func parseWebrpcGenVersions(header string) (*WebrpcGenVersions, error) {
	versions := strings.Split(header, ";")
	if len(versions) < 3 {
		return nil, fmt.Errorf("expected at least 3 parts while parsing webrpc header: %v", header)
	}

	_, webrpcGenVersion, ok := strings.Cut(versions[0], "@")
	if !ok {
		return nil, fmt.Errorf("webrpc gen version could not be parsed from: %s", versions[0])
	}

	tmplTarget, tmplVersion, ok := strings.Cut(versions[1], "@")
	if !ok {
		return nil, fmt.Errorf("tmplTarget and tmplVersion could not be parsed from: %s", versions[1])
	}

	schemaName, schemaVersion, ok := strings.Cut(versions[2], "@")
	if !ok {
		return nil, fmt.Errorf("schema name and schema version could not be parsed from: %s", versions[2])
	}

	return &WebrpcGenVersions{
		WebrpcGenVersion: webrpcGenVersion,
		CodeGenName:      tmplTarget,
		CodeGenVersion:   tmplVersion,
		SchemaName:       schemaName,
		SchemaVersion:    schemaVersion,
	}, nil
}
